[package]
name = "live-slides"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
libc = "0.2"
tauri = { version = "2", features = [] }
ls-contracts = { path = "../../crates/contracts" }
ls-pipeline = { path = "../../crates/pipeline" }
ls-canvas = { path = "../../crates/canvas" }
serde_json = "1"
anyhow = "1"
